services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es01
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9200:9200"   # Elasticsearch REST API
      - "9300:9300"   # Elasticsearch transport
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
